# Generated by Django 4.2.20 on 2025-03-21 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="external_order_id_bueno",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="external_order_id_melange",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
